### ISSUE TITLE
Uncaught TypeError: this.brackets is not iterable

### ISSUE THREAD

**Issue by DannyDannyDanny** [vn-ki/bracket-colorizer#17]
Bracket Colorizer crash when editing `styles.less`. Can be avoided by temporarily disabling the Bracket Colorizer package.

### Steps to reproduce:
1. Open Atom settings -> Packages -> Bracket Colorizer (settings page)
2. Open `style.less` via menu bar: Atom -> Stylesheet...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.3
**Thrown From**: [bracket-colorizer](https://github.com/vn-ki/bracket-colorizer) package 1.3.0

### Stack Trace

Uncaught TypeError: this.brackets is not iterable

```
At /Users/USER/.atom/packages/bracket-colorizer/lib/bracket-matcher.js:26

TypeError: this.brackets is not iterable
    at BracketMatcher.colorBrackets (/packages/bracket-colorizer/lib/bracket-matcher.js:26:30)
    at /packages/bracket-colorizer/lib/bracket-matcher.js:9:10)
    at Object.processEditor (/packages/bracket-colorizer/lib/bracket-colorizer.js:95:23)
    at /packages/bracket-colorizer/lib/bracket-colorizer.js:50:86
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1172021)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1173462)
    at stoppedChangingActivePaneItemTimeout.setTimeout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:425838)
```

### Commands

```
     -3:29.7.0 core:confirm (input.hidden-input)
     -3:29.7.0 settings-view:change-themes (input.hidden-input)
     -2:49 settings-view:open (input.hidden-input)
  3x -2:27.9.0 core:move-left (input.hidden-input)
     -2:26.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
  7x -2:18.4.0 core:undo (input.hidden-input)
  9x -2:15.7.0 core:redo (input.hidden-input)
     -2:13.7.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:13.1.0 core:backspace (input.hidden-input)
     -1:30.2.0 core:copy (div.package-readme.native-key-bindings)
     -1:22.7.0 core:backspace (input.hidden-input)
     -1:12.7.0 core:copy (div.package-readme.native-key-bindings)
     -0:13.6.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:13.4.0 core:paste (input.hidden-input)
  2x -0:08.8.0 core:backspace (input.hidden-input)
     -0:07.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
bracket-colorizer 1.3.0 
highlight-selected 0.16.0 
Hydrogen 2.8.0 
language-gfm-enhanced 0.92.0 
markdown-preview-enhanced 0.15.10 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
pdf-view 0.71.0 
python-indent 1.1.7 
vim-mode-plus 1.36.0 
```

**Comment by UziTech** [comment]
I'm not able to reproduce this. Would you mind sharing your `style.less`?

**Comment by UziTech** [comment]
Could you also share your "Brackets to match" setting value?

**Comment by DannyDannyDanny** [comment]
Funny, now I can't reproduce it myself. I wish I'd taken a screencap. Seems like there was another factor.

I don't think it'll help, but here's my `style.less` nonetheless:

```
atom-text-editor.editor {
  .bracket-colorizer-color0 {
    color: rgb(1, 204, 190);
  }
  .bracket-colorizer-color1  {
    color: teal;
  }
  .bracket-colorizer-color2 {
    color: violet;
  }
  .bracket-colorizer-color3 {
    color: orange;
  }
  .bracket-colorizer-color4 {
    color: red;
  }
  .bracket-colorizer-color5 {
    color: rgb(249, 98, 98);
  }
}
```
