### ISSUE TITLE
Failed to activate the bracket-colorizer package

### ISSUE THREAD

**Issue by jxeer** [vn-ki/bracket-colorizer#52]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.2.3
**Thrown From**: [bracket-colorizer](https://github.com/vn-ki/bracket-colorizer) package 1.4.0

### Stack Trace

Failed to activate the bracket-colorizer package

```
At Cannot find module 'minimatch'
Require stack:
- /Users/generalassembly/.atom/packages/bracket-colorizer/lib/bracket-colorizer.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

Error: Cannot find module 'minimatch'
Require stack:
- /Users/generalassembly/.atom/packages/bracket-colorizer/lib/bracket-colorizer.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at /packages/bracket-colorizer/lib/bracket-colorizer.js:4:47)
    at /packages/bracket-colorizer/lib/bracket-colorizer.js:151:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at requireModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1191586)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3402829)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3390813)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3390591
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3388169)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3390451
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3390394)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:385497)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:385113
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334641)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:385063)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:384613)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:778471
    at async Promise.all (index 0)
```

### Commands

```
```

### Non-Core Packages

```
apex-adapt-dark-ui 0.4.2 
Apex-ui-dark 0.4.0 
atom-beautify 0.33.4 
atom-bracket-highlight 0.3.2 
atom-bright-dark-syntax 1.0.1 
atom-dark-minimal-syntax 0.2.8 
atom-dark-minimal-ui 0.5.8 
atom-ternjs 0.20.0 
auto-indent 0.5.0 
awesome-dark-syntax 0.3.1 
bracket-colorizer 1.4.0 
busy-signal 2.0.1 
dark-code-syntax 1.1.2 
dark-contrast-ui 1.0.0 
dark-flat-ui 1.2.4 
dark-md-syntax 0.2.6 
dark-one-dark-syntax 2.3.0 
file-icons 2.1.47 
futurism-dark-syntax 2.1.0 
ghoulish-ui 1.1.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-babel 2.85.0 
language-ejs 0.4.0 
linter 3.3.1 
linter-csslint 2.0.6 
linter-erb 1.1.5 
linter-eslint 8.6.6 
linter-js-yaml 1.4.6 
linter-ui-default 3.3.1 
naturerainbow-dark-syntax 0.0.4 
northem-dark-atom-ui 2.1.0 
nv-dark-syntax 1.4.1 
nv-dark-ui 3.0.8 
oceanic-next 1.0.0 
platformio-ide-terminal 2.10.1 
prettier-atom 0.60.1 
sagan-dark-ui 0.1.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
snow-dark-syntax-patch 0.2.4 
teletype 0.13.4 
Tycho-Dark-Syntax 0.3.0 
volcanic-dark-syntax 0.1.0 
```

**Comment by UziTech** [comment]
Uninstall and reinstall it. This is an APM error.
